[package]
name = "aoc2020"
version = "0.1.0"
authors = ["fayez <ahmedf.higgy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.4.1"
raster = "0.2.0"